CREATE DATABASE blog;
USE blog;

CREATE TABLE users (
   id INT AUTO_INCREMENT,
   username VARCHAR(60),
   password VARCHAR(60),
   PRIMARY KEY (id)
);

CREATE TABLE articles (
   id INT AUTO_INCREMENT,
   title VARCHAR(60),
   author VARCHAR(60),
   summary VARCHAR(10000),
   review MEDIUMTEXT,
   image VARCHAR(255),
   PRIMARY KEY (id)
);

INSERT INTO users (username, password) 
VALUES ('admin', '$2b$10$7PKtD45XBSrh1URarawfU.Xn4XUS95MCfNtsIEDqS83Z74yfQbNXq');

INSERT INTO articles (title, author, summary, review, image) 
VALUES 
   ("The Great Gatsby", "F. Scott Fitzgerald", "The Great Gatsby is widely regarded as one of the masterpieces of American fiction. It tells of the mysterious Jay Gatsby’s grand effort to win the love of Daisy Buchanan, the rich girl who embodies for him the promise of the American dream. Deeply romantic in its concern with self-making, ideal love, and the power of illusion, it draws on modernist techniques to capture the spirit of the materialistic, morally adrift, post-war era Fitzgerald dubbed “the jazz age.” Gatsby’s aspirations remain inseparable from the rhythms and possibilities suggested by modern consumer culture, popular song, the movies; his obstacles inseparable from contemporary American anxieties about social mobility, racial mongrelization, and the fate of Western civilization.", "In 1922, F. Scott Fitzgerald announced his decision to write ”something new--something extraordinary and beautiful and simple + intricately patterned.” That extraordinary, beautiful, intricately patterned, and above all, simple novel became The Great Gatsby, arguably Fitzgerald's finest work and certainly the book for which he is best known. A portrait of the Jazz Age in all of its decadence and excess, Gatsby captured the spirit of the author's generation and earned itself a permanent place in American mythology. Self-made, self-invented millionaire Jay Gatsby embodies some of Fitzgerald's--and his country's--most abiding obsessions: money, ambition, greed, and the promise of new beginnings. ”Gatsby believed in the green light, the orgiastic future that year by year recedes before us. It eluded us then, but that's no matter--tomorrow we will run faster, stretch out our arms farther.... And one fine morning--” Gatsby's rise to glory and eventual fall from grace becomes a kind of cautionary tale about the American Dream. It's also a love story, of sorts, the narrative of Gatsby's quixotic passion for Daisy Buchanan. The pair meet five years before the novel begins, when Daisy is a legendary young Louisville beauty and Gatsby an impoverished officer. They fall in love, but while Gatsby serves overseas, Daisy marries the brutal, bullying, but extremely rich Tom Buchanan. After the war, Gatsby devotes himself blindly to the pursuit of wealth by whatever means--and to the pursuit of Daisy, which amounts to the same thing. ”Her voice is full of money,” Gatsby says admiringly, in one of the novel's more famous descriptions. His millions made, Gatsby buys a mansion across Long Island Sound from Daisy's patrician East Egg address, throws lavish parties, and waits for her to appear. When she does, events unfold with all the tragic inevitability of a Greek drama, with detached, cynical neighbor Nick Carraway acting as chorus throughout. Spare, elegantly plotted, and written in crystalline prose, The Great Gatsby is as perfectly satisfying as the best kind of poem.", "https://m.media-amazon.com/images/I/41JcYHOQjRL.jpg"),
   ("The Hobbit", "J.R.R. Tolkien", "A great modern classic and the prelude to THE LORD OF THE RINGS. Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely traveling any farther than his pantry or cellar. But his contentment is disturbed when the wizard Gandalf and a company of dwarves arrive on his doorstep one day to whisk him away on an adventure. They have launched a plot to raid the treasure hoard guarded by Smaug the Magnificent, a large and very dangerous dragon. Bilbo reluctantly joins their quest, unaware that on his journey to the Lonely Mountain he will encounter both a magic ring and a frightening creature known as Gollum.", "The Hobbit (or There and Back Again) is a fantasy novel written by J.R.R. Tolkien. It follows the adventures of Bilbo Baggins, a hobbit who embarks on an incredible journey. This children's classic and literary masterpiece was first published in 1937 and has since become a treasured work of fantasy literature. Dragons, trolls, and magic await the reader on this memorable adventure. Bilbo, along with his friend Gandalf the Wizard, embarks on an adventure with a band of dwarves that sends them into the wild and the depths of the earth to reclaim the Lonely Mountain from a dragon. Along the way, he meets elves, men, giants, goblins, spiders, eagles, and a strange creature named Gollum. While the tale of the Lord of the Rings has become highly popular in our modern society, The Hobbit is the original story that laid the groundwork for this epic tale to take place. What transpires as a game of riddles and escape from the creature Gollum in the Hobbit is, in fact, the foundation for an entire adventure for the whole of Middle Earth in Bilbo's later years. Inspired by the author's time serving in World War I, The Hobbit builds to a climactic battle in which many characters met throughout the book reappear. This stunning fairytale is one of adventure, lessons learned, and an entire world born of Tolkien's imagination and desire for an English folklore. The Hobbit is a timeless classic that can be appreciated by readers of all ages.", "https://m.media-amazon.com/images/I/5187PQgDScL.jpg"),
   ("I, Robot", "Isaac Asimov", "I, Robot, the first and most widely read book in Asimov’s Robot series, forever changed the world’s perception of artificial intelligence. Here are stories of robots gone mad, of mind-reading robots, and robots with a sense of humor. Of robot politicians, and robots who secretly run the world—all told with the dramatic blend of science fact and science fiction that has become Asimov’s trademark. The Three Laws of Robotics: 1) A robot may not injure a human being or, through inaction, allow a human being to come to harm. 2) A robot must obey orders given to it by human beings except where such orders would conflict with the First Law. 3) A robot must protect its own existence as long as such protection does not conflict with the First or Second Law. With these three, simple directives, Isaac Asimov formulated the laws governing robots’ behavior. In I, Robot, Asimov chronicles the development of the robot from its primitive origins in the present to its ultimate perfection in the not-so-distant future—a  future in which humanity itself may be rendered obsolete.", "Isaac Asimov began his Foundation Series at the age of twenty-one, not realizing that it would one day be considered a cornerstone of science fiction. During his legendary career, Asimov penned over 470 books on subjects ranging from science to Shakespeare to history, though he was most loved for his award-winning science fiction sagas, which include the Robot, Empire, and Foundation series. Named a Grand Master of Science Fiction by the Science Fiction and Fantasy Writers of America, Asimov entertained and educated readers of all ages for close to five decades. He died, at the age of seventy-two, in April 1992. --This text refers to an out of print or unavailable edition of this title. In this collection, one of the great classics of science fiction, Asimov set out the principles of robot behavior that we know as the Three Laws of Robotics. Here are stories of robots gone mad, mind-reading robots, robots with a sense of humor, robot politicians, and robots who secretly run the world, all told with Asimov's trademark dramatic blend of science fact and science fiction. Isaac Asimov was one of the great explainers of the age...It will never be known how many practicing scientists today, in how many countries, owe their initial inspiration to a book, article, or short story by Isaac Asimov'Carl Sagan `Asimov displayed one of the most dynamic imaginations in science fiction'Daily Telegraph `Asimov's career was one of the most formidable in science fiction'The Times.", "https://m.media-amazon.com/images/I/41ED86iNFkL.jpg");